core-test:
    Bti:
        - Create
        - Pin
    BadAccessTest:
        - InvalidMappedAddressFails
    ConditionalVariableTest:
        - BroadcastSignalThreadWait
        - SignalThreadWait
        - ConditionalVariablesTimeout
    ChannelTest:
        - WriteConsumesAllHandles
        - WaitManyIsSignaledOnAnyElementWrite
        - WaitManyIsSignaledForBothWrites
        - ReadWhenEmptyReturnsShouldWait
    ClockTest:
        - ClockMonotonic
        - DeadlineAfter
    ExecutableTlsTest:
        - BasicInitalizersInThread